### ISSUE TITLE
Failing to commit

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#1]
Sometimes, the script is giving "nothing to commit" but I can't track down the Issue.. E.g. revisions 160 and 179 are having this behaviour

**Comment by avivace** [comment]
[160 and 179 diff](https://gbdev.gg8.se/wiki/index.php?title=Memory_Bank_Controllers&diff=179&oldid=160)

pandoc is (correctly) escaping and ignoring mediawiki {{}} media links so the output is the same and git refuses to git add.

We good. Still have to check if that is the case for all the ~15 commits we are missing (total ~210 revisions, but ~190 commits generated)

**Comment by RetroEdit** [comment]
First thing I'll note: the `{{ }}` syntax is called 'transclusion' in the wikitext vernacular, and the pages they refer to are generally pages in the template namespace (you can also transclude other pages with the same syntax, but I won't get into that).

Without further details, it's difficult to tell definitively whether all the revisions where git refused to add were the template transclusion commits. I might have a try at running the script and seeing if it has problems on those specific revisions, but it's somewhat inconvenient that it does git operations for each revision.

What I've noticed with `pandoc` is that it will insert something like the following when a template is missing (with backtick triplets before and after the section, which I can't really show in a Github comment):

```
{=mediawiki}

{{Pandocs|spriterambug}}
```

This might just be an artifact of me running the script multiple times or possibly something else different with my environment.

Here's a list of revision I found adding the templates just from browsing wiki edits of one contributor who was adding the template transclusions: [166](https://gbdev.gg8.se/wiki/index.php?diff=166), [167](https://gbdev.gg8.se/wiki/index.php?diff=167), [170](https://gbdev.gg8.se/wiki/index.php?diff=170), [171](https://gbdev.gg8.se/wiki/index.php?diff=171), [172](https://gbdev.gg8.se/wiki/index.php?diff=172), [173](https://gbdev.gg8.se/wiki/index.php?diff=173), [174](https://gbdev.gg8.se/wiki/index.php?diff=174), [175](https://gbdev.gg8.se/wiki/index.php?diff=175), [176](https://gbdev.gg8.se/wiki/index.php?diff=176), [177](https://gbdev.gg8.se/wiki/index.php?diff=177), [178](https://gbdev.gg8.se/wiki/index.php?diff=178), [179](https://gbdev.gg8.se/wiki/index.php?diff=179), [180](https://gbdev.gg8.se/wiki/index.php?diff=180), [181](https://gbdev.gg8.se/wiki/index.php?diff=181), [182](https://gbdev.gg8.se/wiki/index.php?diff=182), [183](https://gbdev.gg8.se/wiki/index.php?diff=183), [184](https://gbdev.gg8.se/wiki/index.php?diff=184)

When I run the script and just look at the file differences, I'm also getting some other odd things with those specific revision ids, so I'll probably need to look into that further too.
