### ISSUE TITLE
Remove personal considerations / investigations

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#10]
Make the statements impersonal and maybe use a different style when investigating an unknown behaviour?

E.g. https://github.com/gbdev/pandocs/blob/0e60f72f08423d11207c9a7814d2ef4df1c30089/content/SGB_Functions.md#separating-between-sgb-and-sgb2

**Comment by ISSOtm** [comment]
As far as I can tell, this has been taken care of. The regex `\b(?:I(?!/)|me|my|mine)\b` yields no pertinent results.
