### ISSUE TITLE
Consistent text width

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#100]
Should we keep/enforce the 80 columns wrap?

**Comment by adembudak** [comment]
120 is my new normal on coding and documents.

**Comment by ISSOtm** [comment]
I use 100 soft, 120 hard.

That said, for prose(-ish), like `mandoc`, I prefer to put one sentence per line, not enforcing line wraps. Partly because `mandoc` needs a newline after sentence-ending periods, and partly because line wrapping is OK for prose, imo.

**Comment by ISSOtm** [comment]
Duplicate of #333
