### ISSUE TITLE
Game Boy Camera article present but not included

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/pandocs#118]

**Comment by avivace** [comment]
I'd honestly like to have some of the information from @AntonioND 's https://github.com/AntonioND/gbcam-rev-engineer/blob/master/doc/gb_camera_doc_v1_1_1.pdf but I'm not sure all of that fits Pan Docs

**Comment by ISSOtm** [comment]
Isn't this fixed by #478?

**Comment by avivace** [comment]
yep!
