### ISSUE TITLE
Clarify which side S01 and S02 terminals are

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/pandocs#120]

**Comment by avivace** [comment]
Where? Can you give more details?

**Comment by ISSOtm** [comment]
[NR50 and NR51 descriptions](https://gbdev.io/pandocs/#sound-control-registers)

**Comment by ISSOtm** [comment]
Fixed by 9e5f7319e1d894b2c6e28ecd923147f95d5636ad.
