### ISSUE TITLE
Bad formatting on VRAM + OAM accessibility

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#13]
Feedback by @Bananattack on [Discord](https://discordapp.com/channels/303217943234215948/666927302348636160/673967141652791298):

> Some new notes about the VRAM + OAM accessibility make the main points about into a bolded heading, and rehash information the about STAT modes directly underneath - I think this makes it harder to read and navigate, and I think it would be clearer to list the STAT modes in one place, and just make a mention that the accessibility windows are referring to the STAT modes listed elsewhere. I think it's better to list information once and reference it, than repeat things and increase the potential for misinterpretation, or errors

**Comment by ISSOtm** [comment]
Isn't it better now?
