### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#15]

**Comment by saveriomiroddi** [comment]
Hello! Could you write down a specification, more or less vague, of the issue?

I think that, as a starting point, a crude solution may do better than no solution at all, and it's more likely to be provided by somebody (=me :wink:) :smile:

**Comment by avivace** [comment]
Oh hi @saveriomiroddi !
I don't think we have any clear specification of what we need or want now. I was using the markdown -> pdf functionality of the pandoc tool to get something I got decent results but it was missing an actual and working table of contents

**Comment by saveriomiroddi** [comment]
I see, thanks!

**Comment by ISSOtm** [comment]
Closed by #292, as we're not exactly using Vuepress syntax, but something that can be [reasonably parsed](https://github.com/gbdev/pandocs#custom-containers) regardless of the Markdown parser.
