### ISSUE TITLE
Viewport is too "cramped"

### ISSUE THREAD

**Issue by mid-kid** [gbdev/pandocs#17]
The current combination of font size and viewport width seems rather extreme to me, yielding nice views like this on my current laptop:
![](https://cdn.discordapp.com/attachments/558007840045006870/679484730701643795/unknown.png)

This is definitely... readable, and in my opinion would be well-fit for a blog or some piece of recreational writing, but when reading technical documentation I value being able to fit more on my screen, both to minimize scrolling and to better locate myself in the document.

Text really doesn't need to be as huge.

**Comment by avivace** [comment]
Possible solutions to increase the density:

- Bigger container width
- Smaller text size
- Smaller line-height

**Comment by ISSOtm** [comment]
I agree with increasing the container size and decreasing the font somewhat, but I think the line-height is fine as-is.

**Comment by avivace** [comment]
@mid-kid Is it better now? Are you satisfied with the readability/density?

**Comment by mid-kid** [comment]
This works for me. Thank you.
