### ISSUE TITLE
Gray background headers

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#19]
As suggested by @ISSOtm to potentially fix/improve the situation described in #18 , consider gray banded brackground heading/subheadings, as in nocash docs:

![image](https://user-images.githubusercontent.com/14352721/74791426-b27aac00-52ba-11ea-9215-faee0556f0ad.png)

This requires (and thus it's blocked by) #18 consistency in the usage of headings (h1-h4)

**Comment by ISSOtm** [comment]
Not necessarily gray, depending on the color palette we want to have for the page. Variations of green tints could be nice in referring to the console's LCD (though it's [difficult to do right](https://eldred.fr/gb-asm-tutorial)).

**Comment by ISSOtm** [comment]
Closed by #292
