### ISSUE TITLE
Memory Map: rom spaces

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#195]
The bank at 0000-3FFF is able to be swapped around by some MBCs (most notably the MBC1). It should rather be called either "ROM0", "ROM0 space", or "$0000-3FFF"

**Comment by avivace** [comment]
@AlvaroBurnett want to take a look at this too?

**Comment by AlvaroBurnett** [comment]
Maybe "ROM bank X0". Because it can be assigned banks 00, 20, 40, 60.
