### ISSUE TITLE
Add A,B register startup values for different models

### ISSUE THREAD

**Issue by jkotlinski** [gbdev/pandocs#211]
Add A,B register startup values for different models to Power_Up_Sequence.md

**Comment by ISSOtm** [comment]
Note that there may be other differences, notably given the CGB boot ROM's more complex behavior.

- [ ] Different regs in compatibility mode?
- [ ] Different regs if a palette is manually chosen?
- [ ] Different regs if the logo tilemap is written?

We probably also should document the CGB boot ROM's palette & tilemap selection behavior.

**Comment by CasualPokePlayer** [comment]
Taking a quick look, it looks like the only time differences occur is with compatibility mode (and even then, if it is in DMG compatibility mode, then B is dependent on the title in the header and whether you have the right licensee bytes for built in palettes). Manually choosing palettes has no effect, and I'm not sure what you mean by logo tilemap being written?

In DMG Compatibility Mode (& Licensee)
`AF: 1180 ; 1100 for AGB`
`B: Sum of bytes in 0134-0143 inclusive & 0xFF ; +1 & 0xFF if AGB`
`C: 00`
`DE: 0008`
`HL: 007C`
In DMG Compatibility Mode (& Not Licensee)
`AF: 1180 ; 1100 for AGB`
`BC: 0000 ; 0100 for AGB`
`DE: 0008`
`HL: 007C`
In CGB Mode
`AF: 1180 ; 1100 for AGB`
`BC: 0000 ; 0100 for AGB`
`DE: FF56`
`HL: 000D`

Again this was a quick look so I might have missed something.
