### ISSUE TITLE
"Infinite Sex" and tobacco references in cheat section

### ISSUE THREAD

**Issue by pinobatch** [gbdev/pandocs#26]
From ["Shark_Cheats.md" in the "Gamegenie" folder](https://github.com/gbdev/pandocs/blob/develop/content/Gamegenie/Shark_Cheats.md):
> Hexadecimal codes can be then entered for specific games, typically providing things like Infinite Sex, 255 Cigarettes, or Starting directly in Wonderland Level PRO, etc.

The sex and tobacco references sound like Martin "nocash" Korth's brand of humor, as it appears in the cheating devices section of both [Martin's copy of Pan Docs](https://problemkaputt.de/pandocs.htm#gamegeniesharkcheats) and [GBATEK](https://problemkaputt.de/gbatek.htm#gbacheatcodesgeneralinfo). But I'm not sure if this style is what we're going for in our copy.

**Comment by avivace** [comment]
Definitely not. I'll keep this issue up so we can check other parts of the document, too.

**Comment by ISSOtm** [comment]
I have, other time, read enough of the document that I feel confident enough to call this resolved.

Feel free to slap me around with a wet trout if I turn out wrong ;)
