### ISSUE TITLE
Reusing already introduced Terminology ("dots")

### ISSUE THREAD

**Issue by masl123** [gbdev/pandocs#287]
In Chapter "LCD Status Register" you already introduced "dots" as a unit of time for the LCD/PPU. This unit can be reused later in Chapter "Pixel FIFO" where the same Variable is introduced again as clocks or cycles, depending on #286

**Comment by ISSOtm** [comment]
This should probably be fixed by adding a glossary at the top of the document, as per #194, and documenting there just once.
Therefore, closing as subset of that issue.
