### ISSUE TITLE
Easier navigation of Pan Docs

### ISSUE THREAD

**Issue by brainard52** [gbdev/pandocs#289]
I often have multiple tabs open that each have https://gbdev.io/pandocs/ loaded. Right now, the page title is 
<img width="137" alt="Screen Shot 2021-05-16 at 10 55 49 AM" src="https://user-images.githubusercontent.com/1023838/118407348-47429580-b635-11eb-8fa2-3695e7ef1a26.png">

Being able to dynamically update the window/tab title to include the anchored section would be great. For example, I think something akin to 
<img width="190" alt="Screen Shot 2021-05-16 at 10 57 05 AM" src="https://user-images.githubusercontent.com/1023838/118407411-778a3400-b635-11eb-8a8e-c8dbb9bb5aa4.png"> would be perfect for https://gbdev.io/pandocs/#lcd-monochrome-palettes 

Alternatively, being able to track several sections all at once and easily jump between them via hotkeys would be amazing as well. I don't have the ability to mock it up, but I'm imagining a + next to each anchor link which would add an anchor link to a little floating side bar on the left. That way, I can just quickly navigate between sections I want to remember.

Some sort of sane hotkey system to navigate between "bookmarked" sections would be a great addition to that.

**Comment by ISSOtm** [comment]
I just noticed that [gbadoc](https://github.com/gbdev/gbadoc) uses mdBook, perhaps we could switch Pan Docs to that?

**Comment by avivace** [comment]
> I just noticed that [gbadoc](https://github.com/gbdev/gbadoc) uses mdBook, perhaps we could switch Pan Docs to that?

I've been trying mdBook and it's a breeze, but I think it lacks the "info", "warning" and "caution" boxes we use here, so we still need to check how to do that

**Comment by ISSOtm** [comment]
I think the "preprocessors" feature may do the trick. I'll look into it.

**Comment by ISSOtm** [comment]
Closed by #292
