### ISSUE TITLE
Relative valid links give error

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#296]
If I try to link some of the autogenerated pages which are not actual files (like `./print.html`, which exists and works without errors with `mdbook serve`), the build gives error:

```
error: File not found: ./print.html
   ┌─ About.md:34:45
   │
34 │ You can find a one-page version of Pan Docs [here](./print.html). 
   │                                             ^^^^^^^^^^^^^^^^^^^^ File not found: ./print.html

```

**Comment by ISSOtm** [comment]
This can be fixed by simply adding the link to the ignore list.

**Comment by ISSOtm** [comment]
Checked, and yeah, that's the right way to do it.
