### ISSUE TITLE
Single page version is not so single-page

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#297]
We are currently using mdbook printable version as single-page version of Pan Docs but:

- it triggers the print function of the browser on page load
- links still point to the multi page version

**Comment by akumanatt** [comment]
I'm pretty sure this is mdbook's issue. And their intent was to just print the entire document. Not making a separate navigable version of it (although it had to generate a separate page just for this).

**Comment by ISSOtm** [comment]
The print page shall stay as such; we could however use the "custom" renderer to generate a separate, print-less single-page version with "inner" links.
