### ISSUE TITLE
Figures not working in CGB Registers section

### ISSUE THREAD

**Issue by Calindro** [gbdev/pandocs#301]
I couldn't find a related issue and I'm not sure if other sections are affected as well but I noticed that in the CGB Registers section at https://gbdev.io/pandocs/CGB_Registers.html
The images are missing and in the text there are plain-text references to them like `[[1]](imgs/hdma_single_speed.png)`

**Comment by ISSOtm** [comment]
[According to the CommonMark spec](https://spec.commonmark.org/0.29/#link-text), which is what mdBook parses ([with a couple extensions](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/struct.Options.html)), brackets in link text are valid if either balanced or escaped—they are the latter, so it should work.

The question then simply is, whether our preproc messes up, or we found a bug in either of the `cmark` crates.

**Comment by avivace** [comment]
Thanks for looking into this, @ISSOtm . I don't think it's super critical right now, we can just switch to the image syntax we know it's working in the other pages and then look why this particular shorthand is breaking the the parser later

**Comment by ISSOtm** [comment]
This appears to be an upstream bug, which has been linked to just above. Can't do anything else on our end, I'm afraid!
