### ISSUE TITLE
Document STOP weird behavior

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/pandocs#307]
As explained by this graphic:

![STOP behavior flowchart](https://user-images.githubusercontent.com/15271137/124552190-7c988200-de33-11eb-8fa1-22a1b7f9f483.png)
 
(Source: https://twitter.com/liji32/status/1412131307501625353)

**Comment by avivace** [comment]
Can we add this infographic to Pan Docs? @LIJI32

**Comment by ISSOtm** [comment]
Added in f68548d5
