### ISSUE TITLE
mdbook-linkcheck fails to connect to http://www.sii.co.jp

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/pandocs#319]
Pan Docs started failing locally, and apparently, it fails just the same in CI (re-ran the last commit, which was fine before). However, the link works in my browser, so what gives?

**Comment by ISSOtm** [comment]
Interestingly, `curl` reports the same problem ("unable to get local issuer certificate"). No idea if we can do anything about this, besides either removing the link or placing it in the ignore list.

**Comment by avivace** [comment]
Fixed by https://github.com/gbdev/pandocs/commit/5777a7577aa4dfaed2f7ff04604e0066038cf0e6
