### ISSUE TITLE
Allow SVG to be affected by theme

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#322]
https://stackoverflow.com/questions/18434094/how-to-style-svg-with-external-css
https://rust-lang.github.io/mdBook/format/mdbook.html#including-files

**Comment by avivace** [comment]
@ISSOtm this should be documented in the wiki or at least somewhere to help contributors in building SVGs affect-able by the theme..

**Comment by ISSOtm** [comment]
Sounds related to #277.

**Comment by ISSOtm** [comment]
I wrote up something [on the wiki](https://github.com/gbdev/pandocs/wiki/SVG-guide); feel free to add any information you deem important or necessary, and ping me if I missed anything.

**Comment by avivace** [comment]
> I wrote up something [on the wiki](https://github.com/gbdev/pandocs/wiki/SVG-guide); feel free to add any information you deem important or necessary, and ping me if I missed anything.

Thank you! Looks very nice

**Comment by LIJI32** [comment]
While we're at it, [the use of ClearType here](https://github.com/gbdev/pandocs/blob/master/src/imgs/VGA_versus_CGB.png) is not good for my health.
