### ISSUE TITLE
Sitemap.xml is missing

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#342]
There's no support upstream for generating a sitemap.xml https://github.com/rust-lang/mdBook/issues/1491

**Comment by ISSOtm** [comment]
There is pending support now :) rust-lang/mdBook#1618

**Comment by avivace** [comment]
> There is pending support now :) [rust-lang/mdBook#1618](https://github.com/rust-lang/mdBook/pull/1618)

Can we maintain/keep our version of mdbook somewhere so we don't have to wait for upstream to merge these critical PRs? A sitemap is needed ASAP as it helps a lot with indexing everywhere

**Comment by ISSOtm** [comment]
I've asked about upstream maintainership, if they take too long to reply I'd be okay with forking.

**Comment by avivace** [comment]
I think we should give un on waiting, 0 feedback on that PR

**Comment by ISSOtm** [comment]
Yeah, I guess. :T

**Comment by avivace** [comment]
Done (with a workaround/external tool) in https://github.com/gbdev/pandocs/commit/8eb65d560bb6727d25aa0afc2ea8d1e70431a856
