### ISSUE TITLE
Improve descriptions of sprite position bytes

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#351]
See #346

**Comment by ISSOtm** [comment]
This feels like [the diagram](https://gbdev.io/pandocs/OAM#byte-0--y-position) added in #484 fulfills this? Or should another version be made for the X axis as well?

cc @rondnelson99 and @bfabio from #346.

**Comment by bfabio** [comment]
@ISSOtm that diagram is great and completely clarifies the description for me

**Comment by avivace** [comment]
Thanks for the feedback @bfabio and the work @ISSOtm ! Closing this
