### ISSUE TITLE
DeadCScroll dead link

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/pandocs#353]
[The original link](https://github.com/BlitterObjectBob/DeadCScroll) is dead, and @BlitterObjectBob hasn't replied yet to my pings for a couple days.

Apparently, [the only surviving version](https://github.com/search?q=deadcscroll) is [a fork of mine from when I was making PRs](https://github.com/ISSOtm/DeadCScroll). Even gb-archive doesn't have it.

What should we do?

**Comment by avivace** [comment]
>  Even gb-archive doesn't have it.

This is quite strange, as gb-archive should have updated forks of every git repository mentioned in the awesome-gb list.. 

Also, the gb-archive script should parse Pan Docs for links too..
