### ISSUE TITLE
Anchor links not working in Chromium based browsers

### ISSUE THREAD

**Issue by mattrberry** [gbdev/pandocs#38]
Links to headers like https://gbdev.io/pandocs/#vram-background-maps seem to work in Firefox but not in Chrome

**Comment by basxto** [comment]
It that does not work, then your browser does not support html5.

**Comment by avivace** [comment]
I can confirm I can reproduce this on Chromium 81.0.4044.92 on Debian Sid.

**Comment by JL2210** [comment]
I've been noticing this issue on other websites, too. If you click a link to a header it just sends you to the page instead of the header. I think it's a Chromium bug.

Chrome OS 81.0.4044.141

**Comment by mattrberry** [comment]
Yeah, whether or not it's a chromium bug, there are still some sites that behave as expected. Here's another working example in case it helps: [https://rednex.github.io/rgbds/gbz80.7.html#DEC__HL_](https://rednex.github.io/rgbds/gbz80.7.html#DEC__HL_)

**Comment by basxto** [comment]
On 83.0.4103.61 it only breaks for me when I allow JavaScript in uMatrix.

**Comment by avivace** [comment]
Related: https://stackoverflow.com/questions/38588346/anchor-a-tags-not-working-in-chrome-when-using
