### ISSUE TITLE
The Memory Map section should say whether 16 bit information stored in memory is big endian or little endian.

### ISSUE THREAD

**Issue by tatewilhelm** [gbdev/pandocs#386]
This kinda confused me for a bit when I was looking through

**Comment by ISSOtm** [comment]
It's neither, endianness is determined by how RAM is being used by your code. (You can even mix both if you want.)

The Memory Map section does not deal with anything that has intrinsic enadianness, unlike e.g. [the CGB DMA registers](https://gbdev.io/pandocs/CGB_Registers.html#lcd-vram-dma-transfers) which specify the endianness explicitly.

**Comment by pinobatch** [comment]
Then which part of the document is appropriate for documenting byte order of values stored by `push`, `call`, `rst`, and `ld [a16], sp`, and values read by `pop` and `ret`?

**Comment by ISSOtm** [comment]
Their respective instruction descriptions—none of which are linked to the aforementioned section.

**Comment by ISSOtm** [comment]
@tatewilhelm is this resolved?
