### ISSUE TITLE
RFC: List of hardware registers

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#399]
Following a thread by @aaaaaa123456789 : should there be a page with a comprehensive list of all the available hardware registers, their address, etc (linked?)

Maybe there's a way to automatically generate it from hardware.inc? (at least the first time)

**Comment by ISSOtm** [comment]
What would it be useful for?

**Comment by aaaaaa123456789** [comment]
I've had to look up "what register is at this address" many, many times. It's generally an annoying thing to search on the current documentation.

**Comment by ISSOtm** [comment]
Then the table would simply need to be:

Addr | Name
-----|-----
$FF00 | [`P1`](https://gbdev.io/pandocs/Joypad_Input.html#ff00---p1joyp---joypad-rw)
$FF01 | [`SB`](https://gbdev.io/pandocs/Serial_Data_Transfer_(Link_Cable).html#ff01---sb---serial-transfer-data-rw)

and so on.

**Comment by aaaaaa123456789** [comment]
I'd add a short description and perhaps read/write access flags, but yeah, not much more is needed.

**Comment by Rangi42** [comment]
So, with all the same information as each Pan Docs subheading:

| Addr | Name | Description | R/W |
| --- | --- | --- | --- |
| $FF00 | [`P1`](https://gbdev.io/pandocs/Joypad_Input.html#ff00---p1joyp---joypad-rw) | Joypad | R/W |
| $FF01 | [`SB`](https://gbdev.io/pandocs/Serial_Data_Transfer_(Link_Cable).html#ff01---sb---serial-transfer-data-rw) | Serial data transfer | R/W |
| $FF13 | [`NR13`](https://gbdev.io/pandocs/Sound_Controller.html#ff13---nr13---channel-1-frequency-lo-write-only) | Channel 1 Frequency lo | W |

(The doc headings and table descriptions could also standardize on title or sentence case, and one low/high notation: any of "lo", "Lo", "(lo)", "Low", etc.)

**Comment by aaaaaa123456789** [comment]
> The doc headings and table descriptions could also standardize on title or sentence case, and one low/high notation: any of "lo", "Lo", "(lo)", "Low", etc.

I personally prefer "low"/"high" and sentence case, but maybe that's a topic for another issue?
