### ISSUE TITLE
Spelling: American or British english?

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#413]
We mostly use american variants for now (e.g. behavior, color, ..), but we're not consistent

**Comment by ISSOtm** [comment]
I prefer British; I'm more used to typing American because it's more common online.

**Comment by avivace** [comment]
> I prefer British; I'm more used to typing American because it's more common online.

Sorry I don't get what you're voting for, should we go for British even if we're more used to AE?

**Comment by ISSOtm** [comment]
Yes, British.

**Comment by avivace** [comment]
Okay, I would suggest AE to make as small changes as possible, since most of the document is currently in AE

**Comment by pinobatch** [comment]
There's a [WP:TIES](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Strong_national_ties_to_a_topic) argument in favor of American because the "Game Boy Color" wordmark is in American.

**Comment by avivace** [comment]
Let's go with AE, most of the document is with that already anway.

Updated the wiki accordingly: https://github.com/gbdev/pandocs/wiki/Document-Style
