### ISSUE TITLE
NR31 descriptions assume it's 6-bit, not 8-bit

### ISSUE THREAD

**Issue by heimskr** [gbdev/pandocs#471]
As far as I know, bits 7 and 6 of NR31 (channel 3 length timer) aren't used, but the docs currently say bits 7 through 0 of NR31 (i.e., the entire byte) are used. In the other three channels, only bits 5 through 0 of NRx1 are used for the length timer, and the docs say "When the length timer reaches 64, the channel is turned off," which suggests that it wouldn't make sense for more than 6 bits to be used anyway. Is this an error in the docs, or is there something I'm missing? I checked all the writes to NR31 in worldmap.vgm and duel.vgm from the Pokémon Trading Card Game for GBC, and the highest value written in either is 0x32, which fits in 6 bits, further suggesting that bits 7 and 6 are unused.

**Comment by ISSOtm** [comment]
According to both [dmg-cpu-inside](https://raw.githubusercontent.com/furrtek/DMG-CPU-Inside/master/Schematics/18_CHANNEL3.png) and [SameBoy](https://github.com/LIJI32/SameBoy/blob/e48eb3515d1056aa779e95946345dd9c6c6ef3a6/Core/apu.c#L1278), the register is indeed 8-bit. This looks like a copy-paste blunder from the CH1 description.

**Comment by heimskr** [comment]
I noticed recently that the [gbdev wiki](https://gbdev.gg8.se/wiki/articles/Gameboy_sound_hardware) shows that the length load is 256-L for channel 3 instead of the usual 64-L. Seems I was wrong.

**Comment by ISSOtm** [comment]
All channels now simply read:

> The higher the [length timer](<#Length timer>), the shorter the time before the channel is cut.

...so this is no longer an issue.
