### ISSUE TITLE
Multiple packages deprecated

### ISSUE THREAD

**Issue by SirGouki** [gbdev/pandocs#48]
When running npm install inside render, the user will get warned that chokidar 2 will break on node v14+.

The suggested fix is to update to chokidar 3.  I've not tested this, and I've not looked into any of the code to see what this may or may not effect.  I merely created this issue to bring it to someone's attention to look at any needed code revisions (I've got 0 node.js experience right now or I'd volunteer to do it myself).

Edit: 
Will update with all the warnings.

Edit 2:

Deprecated with updates:
  chokidar - will break in node v14
  request - https://github.com/request/request/issues/3142
  urix - https://github.com/lydell/urix#deprecated
  resolve-url - https://github.com/lydell/resolve-url#deprecated

No longer supported
  har-valider 5.1.5
  mkdirp 0.3.0 - API change with v1.x
  
Security issues:
  fsevents v1.x - will break in node v14, is using insecure binaries.

That is as far as I get.  npm fails with the error:
"Unexpected end of JSON input while parsing near '....15.1'',''eslint-config' and I can not continue getting the requirements at this point.

![image](https://user-images.githubusercontent.com/11664236/89122924-f93b1780-d490-11ea-8e9f-b71ab1b2521d.png)

**Comment by avivace** [comment]
Those are only warnings, npm install will continue without any breaking error.
Are you on macOS?

**Comment by SirGouki** [comment]
No, windows.  MacOS doesn't show a lettered drive in the terminal normally (I'm not aware of any configuration where any OS other than Windows does this, which is why I didn't say what OS).

Also, I did say they are warnings (save for the last 3 lines).  I did find out that my node install was out-dated so I'm updating it and trying again.

**Comment by avivace** [comment]
Glad you figured that out!
