### ISSUE TITLE
lcd-position-and-scrolling: wrap behavior

### ISSUE THREAD

**Issue by dan-mcdonald** [gbdev/pandocs#502]
It's my understanding that when the value of SCX/SCY are large so that the coordinate would exceed 256, it will wrap over to 0.

**Comment by zlago** [comment]
yes, you literally cant write a value bigger than 255 to an 8 bit register

**Comment by dan-mcdonald** [comment]
The SCX/Y values define the top-left corner of the screen's view of the BG/window area. So if SCY=255 then the first line will be the bottom of the BG/window area and the remaining lines will wrap to rows 0-142, right?

**Comment by zlago** [comment]
yup! the background wraps around

**Comment by dan-mcdonald** [comment]
Is this documented anywhere in the pandocs? It seems like the logical place to mention it is in the scrolling section https://gbdev.io/pandocs/Scrolling.html

**Comment by ISSOtm** [comment]
Seems about right. Would you like to open a PR?

**Comment by alloncm** [comment]
Ill open a PR soon
