### ISSUE TITLE
Make raster images selectively sharp

### ISSUE THREAD

**Issue by SonoSooS** [gbdev/pandocs#507]
While this does not really apply anymore, there is still a raster image present, and there could be raster images embedded into an SVG, so this could still be considered.

Some images should be hinted to the browser to be rendered without a blur filter, as the source images are also sharp. This also increases the readability of the images, and makes them infinitely zoomable.

While I don't know of an SVG like this existing yet, I see strong candidates being made where it would make a lot of sense to embed an emulator screenshot into an SVG (as a raster image, it's too complex and wasteful to turn it into a vector image), and put infographics on top of it in form of vector graphics and text.
Since it's an emulator screenshot, it makes a lot of sense to instruct the browser to remove the blur filter from it.

@zlago has suggested this base stylesheet to work on major browsers:
```CSS
img
{
    -ms-interpolation-mode: nearest-neighbor;
    image-rendering: crisp-edges;
    image-rendering: pixelated;
}
```

There should also be a new rule added to the guidelines with regards to embedding raster images into SVG files.

Also, emulator screenshots, and any images showcasing the Game Boy screen (like recreated in an image editor for example, one current live example can be found on the OAM page under the Y position section) should have the blur filter removed.  
Obviously, imperfect (mostly made by camera - to the screen for example) images should be exempt from this rule, as in those cases the removal of the blur filter makes the image quality worse.

**Comment by ISSOtm** [comment]
To be fair, I think we want crisp upscaling by default: we will have more GB screenshots than pictures of Game Boys.

**Comment by avivace** [comment]
> To be fair, I think we want crisp upscaling by default: we will have more GB screenshots than pictures of Game Boys.

Turns out we have way more images that need be rendered as standard than "pixelated", so I went for the opposite approach, mark the raster one and leave everything else default
