### ISSUE TITLE
Make bits-description table separations more visible

### ISSUE THREAD

**Issue by vizigr0u** [gbdev/pandocs#529]
The tables showing the bit layout can be a bit hard to read sometimes because of the low contrast and very thin lines separating each field.
e.g. 
![image](https://github.com/gbdev/pandocs/assets/1981001/40c908a2-79ed-4b14-940e-bb86f2fa5d8e)
![image](https://github.com/gbdev/pandocs/assets/1981001/636b741e-6dc7-46b9-ab4a-5e05183ff3e9)

(Issue exists for every theme)

Example of what a higher contrast would look like on the navy skin:
![image](https://github.com/gbdev/pandocs/assets/1981001/018be8d4-2340-4724-917e-6d42b5e4c4e5)

 (changing `--table-border-color` to `hsl(210, 25%, 33%)` from `hsl(210, 25%, 13%)`)

**Comment by ISSOtm** [comment]
Yeah, seems fair. Can you open a PR?

**Comment by vizigr0u** [comment]
> Yeah, seems fair. Can you open a PR?

I quickly searched the repo for `--table-border-color` and couldn't find it so I figured it would be much faster for someone with the setup on their machine

**Comment by ISSOtm** [comment]
Yeah, those are [provided by mdBook](https://github.com/rust-lang/mdBook/blob/090eba0db5026982c72f20352947cb1438c9f008/src/theme/css/variables.css); those can be overridden (e.g. `.ayu .bit-descrs`) in `custom/style.css`.

**Comment by vizigr0u** [comment]
gotcha, I will try to get the repo setup on my machine and I'll make a PR

**Comment by ISSOtm** [comment]
Fixed by #531.
