### ISSUE TITLE
SGB command packet transfers are described using wrong bits of JOYP

### ISSUE THREAD

**Issue by Zarithya** [gbdev/pandocs#546]
On the page for SGB Command Packet Transfers, they are consistently described as using bits 6 and 7 of the JOYP register, when in reality it should be bits 4 and 5. This is described correctly [on the old version of the docs](https://gbdev.gg8.se/wiki/articles/SGB_Functions#SGB_Command_Packet_Transfers):

> Command packets (aka Register Files) are transferred from the gameboy to the SNES by using P14 and P15 output lines of the JOYPAD register (FF00h), these lines are normally used to select the two rows in the gameboy keyboard matrix (which still works).

Proof that this is indeed how the feature works can be found in the code for games such as [Pokemon Gold](https://github.com/pret/pokegold/blob/master/engine/gfx/color.asm#L712), where the values $10 (a 1 bit), $20 (a 0 bit), and $30 (no data) are used for the transfer.

**Comment by ISSOtm** [comment]
Right, I missed that. Do you mind opening a PR?
