### ISSUE TITLE
0xFF0F - Interrupt flag, not mentioned in memory layout

### ISSUE THREAD

**Issue by Smileynator** [gbdev/pandocs#550]
In the [Memory Map](https://gbdev.io/pandocs/Memory_Map.html), 0xFFFF is explicitly mentioned, but 0xFF0F is not covered.
It seems to fall under "I/O registers" according to the map, but the I/O registers do not list it either.
Only when you go to the specific page about interrupts is it mentioned.

**Comment by ISSOtm** [comment]
Indeed, seems like it's missing from the "I/O ranges" map. Do you mind opening a PR adding it?

**Comment by Smileynator** [comment]
I think i can, but currently busy. I will try to do it when i got time.

**Comment by ISSOtm** [comment]
Fixed by #553.
