### ISSUE TITLE
Syntax highlighting in Code Blocks - GBZ80

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#6]
Syntax highlighting is provided by Prism. [Here](https://github.com/PrismJS/prism/blob/master/components/prism-asm6502.js)'s an example of language definition (6502 Assembly) for it.

It should be trivial to produce something similar for the RGBDS/GBZ80 style assembly

@ISSOtm worked on [something similar](https://github.com/highlightjs/highlight.js/pull/1659/files) for highlight.js - imo we should just convert that language file in the format PrimJS requires.

**Comment by ISSOtm** [comment]
Fixed by #292 and the [highlight.js plugin](https://github.com/gbdev/highlightjs-rgbasm).
