### ISSUE TITLE
ToC depth

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#60]
We need to revision and possibily rethink how deep is the ToC, since it provides the main way to navigate the document.

From a comment on Discord:
> Yeah, I think that is a key issue in finding info quicky. The video section has only 1 main header but contains a lot of information in subheaders.

**Comment by ISSOtm** [comment]
Couldn't we auto-generate it? Even a `sed` script should be enough to auto-generate one, so it shouldn't be too difficult.

I don't see why we'd want to maintain it manually, either: all good documents the size of Pan Docs begin with a ToC at least 2, maybe 3 levels deep.

**Comment by ISSOtm** [comment]
Basically, we need to auto-gen the ToC.

Here are some questions:
- Should it be entirely auto-generated?
- What depth should it be generated at?
- Should it be all at the beginning, or should sections have their individual ToCs, like GBATEK?

**Comment by ISSOtm** [comment]
Closed by #292
