### ISSUE TITLE
Why are there commas before h2 elements?

### ISSUE THREAD

**Issue by RetroEdit** [gbdev/pandocs#70]
I noticed something while I was casually perusing Pan Docs.

In this CSS file: https://gbdev.io/pandocs/assets/css/0.styles.ba7fe2d2.css

```css
h2 :before{content:",\2009"}
```

This pseudo-element seems like an odd choice. It makes all the mouse hover-triggered `#` anchor links on the left side of `h2` headers have a comma before them, which looks wrong.

**Comment by avivace** [comment]
I have honestly no idea, probably something coming from upstream Vuepress? Should be fixed

**Comment by RetroEdit** [comment]
> Should be fixed
@avivace How will it be fixed? Shouldn't it be as simple as just editing the CSS file and removing that specific rule, or is there more overhead?

(it doesn't appear to be fixed yet, if that's what you were saying)

**Comment by avivace** [comment]
Oopsies, forgot to push
