### ISSUE TITLE
Issues related to work in #59

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#76]
Some more points about the work merged in #59 , raised by @ISSOtm :

For example, "this is a ROM and SRAM" is very much unclear
[11:01 PM]
There is at least one sentence beginning without uppercase
[11:02 PM]
The first line of "Echo RAM" is too long and confusing
[11:03 PM]
The IO reg table is still redundant
[11:03 PM]
The part about "returning" from FExx should mention that reads return $FF, and that writes are ignored as well

**Comment by avivace** [comment]
@ISSOtm can you help me on this?

**Comment by avivace** [comment]
@ISSOtm you initially raised concerns on this. I'm closing this in a couple of days if I don't hear from you.

**Comment by ISSOtm** [comment]
I'm starting work on this again, including fixing formatting. On which of the following did we agree?
- `16KB`
- `16 KB`
- `16KiB`
- `16 KiB`

**Comment by AntonioND** [comment]
I vote for ``16 KiB``

**Comment by aaaaaa123456789** [comment]
`16 KB` should be the best. But did we ever agree on this?

**Comment by ISSOtm** [comment]
`kB` or `KiB`, actually. There was an argument about standardizing on one—I think in #54?

**Comment by AntonioND** [comment]
In the case of the GB it's actually even more confusing because the CPU frequency is exactly 4 MiHz, but people normally say 4 MHz as an approximation.

Defining 1000 = 1024 decades ago was a mistake that even hard drive manufacturers take advantage of, we don't need to make the same mistakes.

**Comment by aaaaaa123456789** [comment]
For units of things other than information, SI prefixes are universally accepted and the value shouldn't be quoted as 4 MHz in reference material. (In fact, it should be quoted as 4,194,304 Hz explicitly (and perhaps even as 2²² Hz in a comment); the long trailing decimal places have obscured the power of two to many people.)
On the other hand, KB, MB, GB for 2¹⁰, 2²⁰, 2³⁰ bytes are almost universal, with few exceptions (not including people who intentionally want to make quantities seem larger). Whenever someone talks about a ROM being 1 MB, they invariably mean that the file is $100000 bytes long, not $F4240.

**Comment by aaaaaa123456789** [comment]
> `kB` or `KiB`, actually. There was an argument about standardizing on one—I think in #54?

It seems like the debate was in #55.

**Comment by Rangi42** [comment]
The binary prefixes `Ki-`, `Mi-`, etc, are 100% unambiguous. "KB, MB, GB for 2¹⁰, 2²⁰, 2³⁰" used to be more common, but hard drives' advertised space and even OS-displayed file sizes (macOS and [some](https://superuser.com/questions/938234/size-of-files-in-windows-os-its-kb-or-kb#comment1275467_938259) Linux distros) are now the smaller 10-based quantities.

**Comment by aaaaaa123456789** [comment]
I see them as pointless clutter. (And I have no idea of why macOS and those Linux distros would make such a bad choice; the decimal file size is virtually always less relevant than the binary file size, even to the average user.) Virtually everyone who uses the "old" units still means their binary quantities; I have yet to see _anyone_ talking about a 2.1 MB ROM or a 4.1 KB WRAM bank.

**Comment by Rangi42** [comment]
It's not even an entirely recent inconsistency. The common "1.44 MB" floppy disk size held 1,474,560 bytes: 1.44 × 1024 × 1000.

**Comment by pinobatch** [comment]
Or consider a "700 MB" CD-R, which when burned in mode 1 or mode 2 form 1 holds 80 \* 60 \* 150 KiB = 720000 KiB, or about 703.12 MiB or 737.28 MB.

**Comment by aaaaaa123456789** [comment]
> Or consider a "700 MB" CD-R, which when burned in mode 1 or mode 2 form 1 holds 80 * 60 * 150 KiB = 720000 KiB, or about 703.12 MiB or 737.28 MB.

In this case, the 700 was clearly an approximation of the accurate figure of 703⅛.

**Comment by Rangi42** [comment]
Once you know that the true capacity was 703.12 MiB, it's clear that "700 MB" was rounding, but there's no prior reason to expect "700 MB" to have been rounded.

This is why "MiB" isn't pointless: you don't have to say "Virtually everyone" or "almost universal, with few exceptions", because literally everyone means 1,048,576 bytes when they say "1 MiB".

(People talk about "1 MB" and "2 MB" ROMs because historically that's been accurate, but if a macOS user sees their out.gb file listed as 1.04 MB, that could be confusing.)

**Comment by avivace** [comment]
So the alternatives are KiB vs kB?

**Comment by Rangi42** [comment]
Even if the docs don't use binary prefix "KiB", then still "KB" is the one that (usually) means 1024 bytes; "kB" means 1000. ([Wikipedia](https://en.wikipedia.org/wiki/Kilobyte): "One kilobyte is 1000 bytes. The internationally recommended unit symbol for the kilobyte is kB. [...] The binary meaning of the kilobyte for 1024 bytes typically uses the symbol KB, with an uppercase letter K.")

**Comment by avivace** [comment]
Given that we will need an info box about the adopted units at the start of the document anyway, I think we can vote on this.

Please upvote the message with your preferred solution.

**Comment by avivace** [comment]
Binary Prefixes (Ki, Mi). E.g.:

```
1 MiB = 2^20 bytes = 1,048,576 bytes
1 KiB = 2^10 bytes = 1,024 bytes
```

**Comment by avivace** [comment]
Regular prefixes for binary superunits. E.g.

```
1 MB = 2^20 bytes = 1,048,576 bytes
1 KB = 2^10 bytes = 1,024 bytes
```

**Comment by JL2210** [comment]
Given that we're not talking about storage media here, I don't think explicitly using binary suffixes is necessary.

**Comment by wheremyfoodat** [comment]
KB is less of an eyesore than KiB, more well-known and it's widely agreed to be equal to 1024 bytes.

**Comment by pinobatch** [comment]
Though handhelds and Super Game Boy 2 operate at a nominal 4 MiHz ≈ 4.194 MHz, NTSC Super Game Boy's T-state rate is easiest to express in MHz, namely 189/44 MHz ≈ 4.295 MHz.

Telecommunication has its own convention of bitrates always using decimal prefixes, dating back to the phone system's choice of 8000 samples per second. This continued into the definitions of IDSN, DSL, T1, and Ethernet over twisted pair (10BASE-T, 100BASE-TX, 1000BASE-T, etc.). Thus serial runs at 8.192 kbps not 8 kbps.

**Comment by aaaaaa123456789** [comment]
@pinobatch I'm fairly certain the debate here is only about multiples of bytes, not other units.

**Comment by avivace** [comment]
Thanks for the feedback. This discussion has been incorporated into the [Pan Docs document style](https://github.com/gbdev/pandocs/wiki/Document-Style).
