### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#8]
Everything is broken :)
Wiki links and internal (anchor) links must be cleaned up and updated.
Some external links needs to be fixed, too.

**Comment by RetroEdit** [comment]
Partly addressed by 202f1abb8f338bc02904db0bf8c672d1f28a80f4 (external links need some addressing, and I plan to address that soon).

**Comment by avivace** [comment]
Great! Thank you

**Comment by avivace** [comment]
@RetroEdit any update on this?

**Comment by avivace** [comment]
[The new test step of the ci](https://github.com/gbdev/pandocs/blob/develop/.github/workflows/test.yml) ensures every link stays active.
