### ISSUE TITLE
Mistake for NR52

### ISSUE THREAD

**Issue by aljohnston112** [gbdev/pandocs#81]
I am working on a disassembled Pokemon game and came across the following
```
.ch1_rest
    ldh a, [rNR52]
    and %10001110 ; ch1 off
    ldh [rNR52], a
    ld hl, rNR10
    call ClearChannel
    ret 
```
If bit 0-3 are read only, how is this possible?
I looked at the technical reference: [removed] and bit 0-3 are actually read/write.
![NR52](https://user-images.githubusercontent.com/15526105/99160865-98d38d00-26b1-11eb-8343-9a34caa3096e.PNG)

**Comment by AntonioND** [comment]
Pokemon is famous for the amount of bugs it has. This is probably just another one.

Maybe the right thing to do is to go to that fragment of code and leave a comment saying that it is a bug.

**Comment by AntonioND** [comment]
And I think that the R/W part refers to the fact that the top bit of the register is R/W.

**Comment by aljohnston112** [comment]
Is NR10 also read only?
![NR10](https://user-images.githubusercontent.com/15526105/99161631-e6ec8e80-26b9-11eb-87f7-84df5e714a70.PNG)

**Comment by AntonioND** [comment]
No, that one can be written. Many registers have R/W bits, R bits and W bits. It is confusing to say R/W to the register as a whole.

By the way, that manual that you are using is confidential, and you shouldn't be posting here things taken out of it.

**Comment by ISSOtm** [comment]
Yes, the "channel" bits of NR52 can only be read. Writes to them are ignored, so these instructions do nothing:
```
    ldh a, [rNR52]
    and %10001110 ; ch1 off
    ldh [rNR52], a
```
It seems to be a common misbelief, too.

**Comment by aljohnston112** [comment]
After looking through the manual more. It appears you are right, because it never says the register is read from.
