### ISSUE TITLE
Document the GBC approval process

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#83]
Following https://github.com/gbdev/awesome-gbdev/pull/197, we may want to rewrite that part of the manual in pandocs

**Comment by pinobatch** [comment]
I wrote a draft on GbdevWiki: [GBC approval process](https://gbdev.gg8.se/wiki/articles/GBC_approval_process)

**Comment by avivace** [comment]
@pinobatch great, thanks! Already looks okay to me.

Can we keep a single source (either here on pandocs or on the wiki) and just like the other place?

**Comment by avivace** [comment]
Also: do we need this information in Pan Docs?

**Comment by AntonioND** [comment]
I think it's short enough that, even if it is a bit off-topic, is worth staying in Pan Docs. There is nowhere else for it to be.
