### ISSUE TITLE
Standardize pseudocode

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#95]
There's still some syntax from the BASIC era (`<>` for `!=`, ..).

Pseudocode syntax should be standardized to use Python/C style

**Comment by aaaaaa123456789** [comment]
Is there any reason for this besides "I know Python and C"?

**Comment by pinobatch** [comment]
In order to pick the right one, is there an advantage of one over the other?
- C/Python/JS style: `==` for equality and `!=` for inequality
- BASIC/Pascal/SQL/ca65 style: `=` for equality and `<>` for inequality

**Comment by aaaaaa123456789** [comment]
I'd say that `=` is the universally agreed symbol for equality, and since this is pseudocode, the tokenization/parsing ambiguity that caused `==` to be invented is not at all relevant. As for inequality, why not just use `≠`? Are we trying to support browsers from 1999 that don't support Unicode?

**Comment by Rangi42** [comment]
In papers with pseudocode I've sometimes seen math-standard `=` and `≠` for equality/inequality, with `←` for assignment (as in `sum ← 2 + 2`).

**Comment by avivace** [comment]
> Is there any reason for this besides "I know Python and C"?

I don't have a strong opinion on that, I just want to set a standard rule to follow.

I tought maybe following a language syntax gives a more "familiar" look to the pseudocode? Are there examples of people writing pseudocode with `≠`?

**Comment by aaaaaa123456789** [comment]
≠ is mathematical notation that everyone knows and understands; it's (hopefully) taught in primary school. Same with =. I don't have any pseudocode examples at hand (using that syntax or any other), but it's certainly common.
After all, pseudocode is _not_ code.

**Comment by Rangi42** [comment]
Arguably C operators would also be okay since it's similarly low-level and snippets of it map well to asm. Like `ld a, [hli]` being `a = *hl++`.

But yes, there's plenty of pseudocode that uses ≠ and other Unicode: https://en.wikipedia.org/wiki/Pseudocode#Mathematical_style_pseudocode

**Comment by aaaaaa123456789** [comment]
Someone unfamiliar with C wouldn't know if that mapped to `*(hl ++)` (as it does) or `(*hl) ++`. That's generally not too great.

**Comment by pinobatch** [comment]
Especially because those correspond almost perfectly to the instructions `ld a, [hl+]` and `inc hl`.

**Comment by avivace** [comment]
How about:

- Assignment: ← or :=
- Comparison: =, ≠, <, >, ≤, ≥
- Arithmetic: +, −, ×, /, mod
- Floor/ceiling: ⌊, ⌋, ⌈, ⌉a ←    ⌊b⌋    + ⌈c⌉
- Logical: and, or
- Sums, products: Σ Π

References: http://www.cs.cornell.edu/courses/cs482/2003su/handouts/pseudocode.pdf , https://blog.usejournal.com/how-to-write-pseudocode-a-beginners-guide-29956242698

**Comment by JL2210** [comment]
> /, mod

maybe ÷ and % instead?

**Comment by AntonioND** [comment]
I'm not a fan of % because it's also used for percentages.

**Comment by avivace** [comment]
> > /, mod
> 
> maybe ÷ and % instead?

What's wrong with `/`?

**Comment by aaaaaa123456789** [comment]
`/` is standard (see: fractions), so I see no issues with it.

**Comment by Rangi42** [comment]
Also ÷ can be hard to distinguish from +.

**Comment by avivace** [comment]
Added to the Pan Docs document style guide: https://github.com/gbdev/pandocs/wiki/Document-Style
