### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by avivace** [gbdev/pandocs#96]
Should we enable ligatures for code snippets?

https://www.jetbrains.com/lp/mono/#ligatures

**Comment by aaaaaa123456789** [comment]
Please no. These things are hard to read for anyone who isn't used to them.
If we need the special symbols, we should just use them directly; they're all in Unicode.

**Comment by avivace** [comment]
Added to the Pan Docs document style guide: https://github.com/gbdev/pandocs/wiki/Document-Style
