### ISSUE TITLE
FF1B - NR31 - Channel 3 Sound Length - read only?

### ISSUE THREAD

**Issue by vojty** [gbdev/pandocs#97]
`NR31` register appears to be read only.
I don't have real hardware to test it, but many emulators emulate it as read-only and `blarggs-tests/dmg_sound/rom_singles/01-registers.gb` depends on this behaviour

I know these tests are sometimes misleading but for example mooneye, SameBoy or binjgb pass this particular test.

**Comment by ISSOtm** [comment]
I'm assuming you meant "write-only", otherwise it doesn't make much sense :P

And if so, this was fixed by 50310f4a3d5d0fd7a884aa2661e5ae8e52c9a612.
